name: analysis
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bedtools=2.31.0
  - blas=1.0
  - bottleneck=1.3.5
  - bowtie2=2.5.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cffi=1.15.1
  - contourpy=1.0.5
  - curl=8.2.1
  - cutadapt=4.4
  - cycler=0.11.0
  - dbus=1.13.18
  - dnaio=1.0.0
  - expat=2.5.0
  - fastqc=0.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - gdbm=1.18
  - giflib=5.2.1
  - glib=2.69.1
  - icu=73.1
  - intel-openmp=2023.1.0
  - isa-l=2.30.0
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.2.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libnghttp2=1.52.0
  - libpng=1.6.39
  - libssh2=1.10.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.10.4
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-base=3.7.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.0.7
  - ncurses=6.4
  - numexpr=2.8.4
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openjdk=11.0.13
  - openssl=3.1.3
  - packaging=23.1
  - pandas=2.0.3
  - pbzip2=1.1.13
  - pcre=8.45
  - perl=5.34.0
  - pigz=2.6
  - pillow=9.4.0
  - pip=23.2.1
  - pycparser=2.21
  - pyparsing=3.0.9
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-isal=1.1.0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - readline=8.2
  - rename=1.601
  - samtools=1.6
  - scikit-learn=1.3.0
  - scipy=1.11.1
  - seaborn=0.12.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - trim-galore=0.6.10
  - tzdata=2023c
  - wheel=0.41.2
  - xopen=1.7.0
  - xz=5.4.2
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
prefix: /storage/home/hcoda1/0/pxu64/.conda/envs/analysis
